# DATASETS 

<h1 style="font-size:150%;text-decoration:underline">INFORME DE VIRUS</h1>


**Group:** Nombre del grupo de administración al cuál pertenece el dispositivo.

**Device:** Nombre del dispositivo evaluado.

**Detected object:** Nombre tecnico del virus dado por Kaspersky.

**Detected at:** Fecha y hora de detección del virus.

**Path to file:** Ruta de red donde se ha detectado el malware.

**Object type:** Clasificación del tipo de objeto detectado.

**Details:** Breve descripción detallada sobre el malware.

**Action:** Acción tomada sobre el malware.

**Account:** Nombre de la cuenta de usuario en el dispositivo.

**Application:** Nomble completo de la aplicación.

**Version number:** Versión del virus detectado.

**Last visible:** Fecha y hora del dispositivo que se vuelve visible en la red.

**Last connected to Administration Server:** Fecha y hora del último dispositivo conectado al servidor de administración.

**IP address:** Dirección de red del dispositivo.

**NetBIOS name:** Nombre del equipo testeado.

**Windows domain:** Nombre del dominio windows local o remoto.



**La base Informe de Virus es una base obtenida de un appliance de seguridad proveniente de una empresa del sector Educativo.**


