--- 
title: "A Vulnerability Prediction Analysis"
author: "Luis Guerra, Elmer Oliveros, Roger Chauca"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
description: |
  I created this project with the aim to express how a vulnerability can be interpreted using a graphical representation based on a information sample dataset caught from antivirus public database.
---

```{r eval=TRUE}
library(forecast)
library(lubridate)
library(tidyverse)
library(readr)
library(markdown)
library(plotrix)
library(gganimate)
library(gifski)

Informe_de_virus <- read_delim("Informe de virus.csv",delim = ";", escape_double = FALSE, trim_ws = TRUE)
```

# OBJETIVOS

Realizar un análisis y estudio de un conjunto de eventos y/o incidentes de seguridad informática que han sido generados por diferentes estaciones de trabajo y/o usuarios de una empresa al usar los recursos de red, para poder determinar cuál es tipo de malware más común, bajo que escenario se han producido estos eventos, así como investigar e intentar predecir la cantidad de eventos a futuro.

Para poder llevar a cabo este estudio se dispone de datasets obtenidos de dispositivos de seguridad de la empresa.

Los objetivos típicos son comprender:

*	La distribución de variables en su conjunto de datos. 
*	Las relaciones entre variables.
*	Si sus datos tienen o no valores atípicos o puntos inusuales puede indicar problemas de calidad de los datos o conducir a descubrimientos interesantes.

